export const GOOGLE_ID_TOKEN_USER = 'google-id-token-user'
export const GOOGLE_ID_TOKEN_STUDENT = 'google-id-token-student'
export const JWT_AUTH_USER = 'jwt-auth-user'
export const JWT_AUTH_ADMIN = 'jwt-auth-admin'
export const JWT_AUTH_GUEST = 'jwt-auth-guest'
export const PERMISSIONS = 'permissions'
export const ANY_PERMISSION = '*'
export const NO_AUTH = 'no_auth'