export const USER_TOKEN = 'user_token'
export const GUEST_TOKEN = 'guest_token'
export const JWT_AUTH_USER = 'jwt-auth-user'
export const JWT_AUTH_ADMIN = 'jwt-auth-admin'
export const JWT_AUTH_GUEST = 'jwt-auth-guest'
export const PERMISSIONS = 'permissions'
export const ANY_PERMISSION = '*'
export const NO_AUTH = 'no_auth'